"""Stage the M5 owner-auth probe upload directories (design §3 unit 4); no cloud calls.

  python -m scripts.pft_m5_stage_auth_probe --destination DIR

DIR/api: main.py wrapper, experiments/m5_cloud/{auth_probe,auth_api_probe}.py, requirements.txt,
         .python-version, vercel.json, supabase-ca.crt (pinned fingerprint), SHA256SUMS.
DIR/web: the WEB_FILES manifest of experiments/m5_cloud/auth_web_probe, SHA256SUMS.
The destination must be new and outside the repository. Any other file in the web source outside
node_modules/.next/.vercel (env, .npmrc, keys, logs, symlinks) stops staging; none is copied.
"""
import argparse
import hashlib
import json
from pathlib import Path
import shutil
import ssl

from deploy.backup_runner.stage_backup_repo import CA_SHA256
from scripts.pft_m5_prepare_cloud_bundle import check_entrypoints

ROOT = Path(__file__).resolve().parents[1]
API_SOURCES = ("experiments/m5_cloud/auth_probe.py", "experiments/m5_cloud/auth_api_probe.py")
WEB_SOURCE = ROOT / "experiments" / "m5_cloud" / "auth_web_probe"
WEB_FILES = ("app/api/pft/probe/[op]/route.js", "app/layout.js", "app/login/page.js", "app/page.js",
             "app/probe/page.js", "app/probe/probe-client.js", "lib/config.js", "lib/forward.mjs",
             "lib/forward.test.mjs", "lib/supabase/browser.js", "lib/supabase/middleware.js",
             "lib/supabase/server.js", "middleware.js", "next.config.mjs", "package-lock.json", "package.json")
WEB_EXCLUDED_DIRS = {"node_modules", ".next", ".vercel"}
PINNED = ("fastapi==", "SQLAlchemy==", "asyncpg==", "cryptography==")
EXTRA_REQUIREMENTS = ("PyJWT[crypto]==2.10.1", "httpx==0.28.1")
MAIN_PY = '''"""Vercel entrypoint for the M5 owner-auth API probe (generated by staging; do not edit)."""
from experiments.m5_cloud.auth_api_probe import create_app, load_settings

app = create_app(load_settings())
'''


def requirements():
    lines = [line for line in (ROOT / "api" / "requirements.txt").read_text().splitlines()
             if line.startswith(PINNED)]
    if len(lines) != len(PINNED):
        raise RuntimeError("api/requirements.txt pins changed; review the probe bundle")
    return "\n".join([*lines, *EXTRA_REQUIREMENTS]) + "\n"


def ca_pem():
    pem = (ROOT / "deploy" / "backup_runner" / "supabase-ca.crt").read_text()
    if "PRIVATE KEY" in pem or hashlib.sha256(ssl.PEM_cert_to_DER_cert(pem)).hexdigest() != CA_SHA256:
        raise RuntimeError("supabase-ca.crt does not match the pinned certificate fingerprint")
    return pem


def web_files():
    # Only the reviewed WEB_FILES are uploaded. Anything else outside the build directories (an
    # env file, .npmrc, key, log, unlisted source or symlink) stops staging before any write.
    found = set()
    for path in sorted(WEB_SOURCE.rglob("*")):
        relative = path.relative_to(WEB_SOURCE)
        if WEB_EXCLUDED_DIRS & set(relative.parts):
            continue
        if path.is_symlink() or not (path.is_dir() or relative.as_posix() in WEB_FILES):
            raise RuntimeError(f"Rejected web file: {relative.as_posix()}")
        if path.is_file():
            found.add(relative.as_posix())
    missing = [relative for relative in WEB_FILES if relative not in found]
    if missing:
        raise RuntimeError(f"Missing web file: {missing[0]}")
    return [WEB_SOURCE / relative for relative in WEB_FILES]


def write_sums(directory):
    lines = [f"{hashlib.sha256(path.read_bytes()).hexdigest()}  {path.relative_to(directory).as_posix()}"
             for path in sorted(directory.rglob("*")) if path.is_file() and path.name != "SHA256SUMS"]
    (directory / "SHA256SUMS").write_text("\n".join(lines) + "\n")
    return lines


def stage(destination):
    destination = Path(destination).resolve()
    if destination.exists() or destination.is_relative_to(ROOT):
        raise RuntimeError("Requires a fresh destination outside the repository")
    api_files = {relative: (ROOT / relative).read_text() for relative in API_SOURCES}
    check_entrypoints(["main.py", *API_SOURCES], {"main.py": MAIN_PY, **api_files})
    generated = {**api_files, "main.py": MAIN_PY, "requirements.txt": requirements(),
                 ".python-version": "3.12\n", "supabase-ca.crt": ca_pem(),
                 "vercel.json": json.dumps({"functions": {"main.py": {"maxDuration": 30}}}, indent=2) + "\n"}
    sources = web_files()
    api, web = destination / "api", destination / "web"
    for relative, content in generated.items():
        target = api / relative
        target.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
        target.write_text(content)
    for path in sources:
        target = web / path.relative_to(WEB_SOURCE)
        target.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
        shutil.copyfile(path, target)
    return {"api": write_sums(api), "web": write_sums(web)}


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--destination", type=Path, required=True)
    result = stage(parser.parse_args().destination)
    print(json.dumps({name: len(lines) for name, lines in result.items()}))
